/**
 * The generated hook shim.
 *
 * `init` writes a tiny forwarding script into the project rather than registering
 * Shoot's own `dist/` path directly. Two reasons:
 *
 *   - `node_modules` layout changes across reinstalls; the shim gives the host's
 *     config file a stable path that never needs rewriting.
 *   - It keeps the registered command as plain `node <file>`, avoiding Windows
 *     `.cmd` bin-shim resolution differences entirely.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import * as messages from '../mascot/messages.js';

/** Where the shim lives, relative to the project root. */
export const SHIM_RELATIVE_PATH = join('.claude', 'shoot-hook.js');

/** The path registered in Claude Code's settings, using its project-dir variable. */
export const SHIM_REGISTERED_PATH = '${CLAUDE_PROJECT_DIR}/.claude/shoot-hook.js';

/** Codex keeps its config under `.codex/`, so its shim lives there. */
export const CODEX_SHIM_RELATIVE_PATH = join('.codex', 'shoot-hook.js');

/** Locate the compiled hook entry point that ships with this install. */
export function resolveHookEntry(): string {
  // This file compiles to <dist>/core/shim.js; the hook is at <dist>/commands/hook.js.
  return join(dirname(fileURLToPath(import.meta.url)), '..', 'commands', 'hook.js');
}

/**
 * Write the shim and return its absolute path.
 *
 * The import target MUST be a file:// URL: on Windows `import('D:/...')` fails
 * with ERR_UNSUPPORTED_ESM_URL_SCHEME because "d:" parses as a protocol.
 */
export function writeHookShim(
  cwd: string,
  hookEntryPath: string,
  relativePath: string = SHIM_RELATIVE_PATH,
): string {
  const shimPath = join(cwd, relativePath);
  mkdirSync(dirname(shimPath), { recursive: true });

  const target = pathToFileURL(hookEntryPath).href;

  // The shim is standalone generated code and cannot import messages.ts at
  // runtime, so the canonical string is baked in at generation time.
  const failurePrefix = JSON.stringify(messages.shimLoadFailed(''));

  const contents = `#!/usr/bin/env node
// Generated by \`shoot init\`. Forwards stop events to Shoot.
// Safe to delete via \`shoot uninstall\`.
import('${target}')
  .then((m) => m.runHook())
  .then((code) => process.exit(typeof code === 'number' ? code : 0))
  .catch((err) => {
    // Never break the session — but never fail silently either, or a broken
    // install looks exactly like a clean pass.
    process.stderr.write(${failurePrefix} + err.message + '\\n');
    process.exit(0);
  });
`;

  writeFileSync(shimPath, contents, 'utf8');
  return shimPath;
}
